package ridingSports.carving

import ridingSports.byFeetThrust.Walkable
import ridingSports.mobilityMachine.MobileMachineCondition
import ridingSports.mobilityMachine.MobilityMachineDownForceInPumpingTrack
import ridingSports.snowSports.CarvingMobileMachineEdgeable
interface CarvingCondition: MobileMachineCarvable, MobileMachineCondition , CarvingMobileMachineEdgeable,
Walkable{
    val mobilityMachineDownForceInPumpingTrack: MobilityMachineDownForceInPumpingTrack
}

