package ridingSports.carving

import ridingSports.byFeetThrust.ThrustableOnLimitedGripRoad
import ridingSports.mobilityMachine.MobileMachineCondition
import ridingSports.mobilityMachine.MobilityMachineDownForceInPumpingTrack
import ridingSports.snowSports.CarvingMobileMachineEdgeable
interface CarvingCondition: MobileMachineCarvable, MobileMachineCondition , CarvingMobileMachineEdgeable,
ThrustableOnLimitedGripRoad{
    val mobilityMachineDownForceInPumpingTrack: MobilityMachineDownForceInPumpingTrack
}

