package infomaticCurrency.money.currentizeVariation.ruleForPropertyLifeCycle

import infomaticCurrency.money.currentizeVariation.ruleForPropertyLifeCycle.RuleForMoneyLifeCycle

interface RuleForDeleteMoney : RuleForMoneyLifeCycle {
}