package infomaticCurrency.variationOfCurrentize.ruleForPropertyLifeCycle

import infomaticCurrency.money.currentizeVariation.ruleForPropertyLifeCycle.RuleForMoneyLifeCycle

interface RuleForDeleteMoney : RuleForMoneyLifeCycle {
}