package infomaticCurrency.graphCurrency

import infomaticCurrency.basic.SingleInformaticCurrencyUnit
import infomaticCurrency.functionOfCurrency.CurrencyAttachedTarget

interface SingleGraphCurrencyUnit : SingleInformaticCurrencyUnit {
    val currencyAttachedTarget: CurrencyAttachedTarget
}